# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95daa2d33fcef5713b7f4575f8e92206dece19528101af074fd3df30e0277a52f6b23a3b44a9fea4e17513afcf4b581ac893ebb4dbd792eae5a803e9cb7f18c8

test:
  secret_key_base: 54fbda4503f4505ec194fad9e42ba875ac1bcef8983682fcfa1b9816f5ff9d76dfe9db01f1fbc1228d5336197551feedfbfaf7cb2e0cbe86a86e091deed5360b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
